minimumReleaseAge: 4320

overrides:
  "@vercel/node>path-to-regexp": 6.3.0
  "@vercel/python-analysis>minimatch": 10.2.5
  "@vercel/python-analysis>smol-toml": 1.6.1
  fast-xml-parser: 5.7.1
  follow-redirects: 1.16.0
  lodash: 4.18.1
  lodash-es: 4.18.1
  mermaid: 11.14.0
  serialize-javascript: 7.0.5
