/** @type {import("@docusaurus/plugin-content-docs").SidebarsConfig} */
const sidebars = {
  networkSidebar: [
    {
      type: "autogenerated",
      dirName: "network",
    },
  ],
  apiSidebar: [
    {
      type: "autogenerated",
      dirName: "api",
    },
  ],
  protocolSidebar: [
    {
      type: "autogenerated",
      dirName: "protocol",
    },
  ],
  stackSidebar: [
    {
      type: "autogenerated",
      dirName: "stack",
    },
  ],
  changelogSidebar: [
    {
      type: "autogenerated",
      dirName: "changelog",
    },
  ],
};

module.exports = sidebars;
