/** @type {import("@docusaurus/plugin-content-docs").SidebarsConfig} */
const sidebars = {
  networkSidebar: [
    {
      type: "link",
      label: "Status",
      href: "https://linea.statuspage.io/",
      className: "sidebar-status-link",
    },
    {
      type: "link",
      label: "Bridge",
      href: "https://bridge.linea.build",
      className: "sidebar-bridge-link",
    },
    {
      type: "category",
      label: "Introduction",
      collapsible: false,
      items: [
        "network/quickstart/index",
        "network/overview/index",
      ],
    },
    {
      type: "category",
      label: "Features",
      collapsible: false,
      items: [
        "network/overview/known-finality-state",
        "network/overview/predictable-pricing",
        "network/overview/public-data",
        "network/overview/recoverable-state",
        "network/overview/ethereum-differences",
      ],
    },
    {
      type: "category",
      label: "Resources",
      collapsible: false,
      items: [
        "network/build/index",
        {
          type: "category",
          label: "Launch an app",
          collapsible: true,
          collapsed: true,
          items: [{ type: "autogenerated", dirName: "network/build/launch-an-app" }],
        },
        "network/build/connect",
        "network/build/block-explorers",
        "network/build/bridge",
        "network/build/contracts",
        "network/build/get-testnet-eth",
        "network/build/send-receive-messages",
        {
          type: "category",
          label: "Tools",
          collapsible: true,
          collapsed: true,
          items: [{ type: "autogenerated", dirName: "network/build/tools" }],
        },
      ],
    },
    {
      type: "category",
      label: "How To",
      collapsible: false,
      items: [
        "network/how-to/recover-state",
        "network/how-to/gas-fees",
        "network/how-to/bridge",
        "network/how-to/connect-wallet",
        {
          type: "category",
          label: "Deploy a smart contract",
          collapsible: true,
          collapsed: true,
          items: [{ type: "autogenerated", dirName: "network/how-to/deploy-smart-contract" }],
        },
        "network/how-to/deploy-subdomain",
        "network/how-to/fallback",
        "network/how-to/finalized-block",
        "network/how-to/migrate-dapp",
        {
          type: "category",
          label: "Run a node",
          collapsible: true,
          collapsed: true,
          items: [{ type: "autogenerated", dirName: "network/how-to/run-a-node" }],
        },
        {
          type: "category",
          label: "Verify a smart contract",
          collapsible: true,
          collapsed: true,
          items: [{ type: "autogenerated", dirName: "network/how-to/verify-smart-contract" }],
        },
        {
          type: "doc",
          id: "network/how-to/verify-users-with-proof-of-humanity",
          label: "Verify users with PoH",
        },
      ],
    },
    {
      type: "category",
      label: "Tutorials",
      collapsible: false,
      items: [
        "network/tutorials/aiagent-quickstart",
        {
          type: "category",
          label: "Ecosystem tutorials",
          collapsible: true,
          collapsed: true,
          items: [{ type: "autogenerated", dirName: "network/tutorials/ecosystem-tutorials" }],
        },
        "network/tutorials/first-dapp",
        "network/tutorials/marketplace-dapp",
        "network/tutorials/voting-dapp",
      ],
    },
    "network/risk-disclosures",
  ],
  apiSidebar: [
    {
      type: "category",
      label: "Introduction",
      collapsible: false,
      items: ["api/quickstart"],
    },
    {
      type: "category",
      label: "Reference",
      collapsible: false,
      items: [{ type: "autogenerated", dirName: "api/reference" }],
    },
    {
      type: "category",
      label: "Smart contract reference",
      collapsible: false,
      items: [
        {
          type: "category",
          label: "Interfaces",
          collapsible: true,
          collapsed: true,
          items: [{ type: "autogenerated", dirName: "api/linea-smart-contracts/interfaces" }],
        },
        {
          type: "category",
          label: "lib",
          collapsible: true,
          collapsed: true,
          items: [{ type: "autogenerated", dirName: "api/linea-smart-contracts/lib" }],
        },
        "api/linea-smart-contracts/linearollup",
        {
          type: "category",
          label: "messageservice",
          collapsible: true,
          collapsed: true,
          items: [{ type: "autogenerated", dirName: "api/linea-smart-contracts/messageservice" }],
        },
        {
          type: "category",
          label: "TokenBridge",
          collapsible: true,
          collapsed: true,
          items: [{ type: "autogenerated", dirName: "api/linea-smart-contracts/tokenbridge" }],
        },
        "api/linea-smart-contracts/zkevmv2",
      ],
    },
    "api/linea-sdk",
    "api/token-api/index",
  ],
  protocolSidebar: [
    {
      type: "category",
      label: "Introduction",
      collapsible: false,
      items: [
        "protocol/quickstart",
        "protocol/overview",
      ],
    },
    {
      type: "category",
      label: "Core Stack",
      collapsible: false,
      items: [{ type: "autogenerated", dirName: "protocol/architecture" }],
    },
    {
      type: "category",
      label: "Reference",
      collapsible: false,
      items: [{ type: "autogenerated", dirName: "protocol/reference" }],
    },
    "protocol/tokenomics",
  ],
  stackSidebar: [
    {
      type: "category",
      label: "Introduction",
      collapsible: false,
      items: [
        "stack/quickstart",
        "stack/index",
      ],
    },
    {
      type: "category",
      label: "Architecture and Operations",
      collapsible: false,
      items: [{ type: "autogenerated", dirName: "stack/how-it-works" }],
    },
    {
      type: "category",
      label: "Enterprise Capabilities",
      collapsible: false,
      items: [{ type: "autogenerated", dirName: "stack/features" }],
    },
  ],
  changelogSidebar: [
    {
      type: "autogenerated",
      dirName: "changelog",
    },
  ],
};

module.exports = sidebars;
