---
name: Check file name case

on:
  pull_request:
    branches: [ main ]
    paths: ['docs/**']

permissions: {}

jobs:
  case:
    name: Check for case being inconsistent
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ["docs"]
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Case check action
        uses: ConsenSys/github-actions/docs-case-check@68e0677c7c567c2447fc82d43dc4fceb4b31a680
        with:
          DOC_DIR: ${{ matrix.folder }}
