---
name: Check file name case

on:
  pull_request:
    branches: [ main ]
    paths: ['docs/**']

permissions: {} # lock everything by default (least-privilege)

jobs:
  case:
    name: Check for case being inconsistent
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ["docs"]
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Case check action
        uses: Consensys/github-actions/docs-case-check@3a2429772a5d3653f0662a6a66299cad96e74196 # main
        with:
          DOC_DIR: ${{ matrix.folder }}
