---
name: Check file name case

on:
  pull_request:
    branches: [ main ]
    paths: ['docs/**']

permissions: {}

jobs:
  case:
    name: Check for case being inconsistent
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ["docs"]
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Case check action
        uses: ConsenSys/github-actions/docs-case-check@68e0677c7c567c2447fc82d43dc4fceb4b31a680
        with:
          DOC_DIR: ${{ matrix.folder }}
