---
name: Check for broken links

on:
  pull_request:
    branches: [ main ]

permissions: {}

jobs:
  linkCheck:
    name: Link Checking
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: LinkCheck
        uses: Consensys/github-actions/docs-link-check@8e207ec2ad53d90ab419d39d03084fa93e04d190
        with:
          CONFIG_FILE: '.linkspector.yml'
