---
name: Check for broken links

on:
  pull_request:
    branches: [ main ]

permissions: {}

jobs:
  linkCheck:
    name: Link Checking
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: LinkCheck
        uses: Consensys/github-actions/docs-link-check@68e0677c7c567c2447fc82d43dc4fceb4b31a680
        with:
          CONFIG_FILE: '.linkspector.yml'
