---
name: Check for broken links

on:
  pull_request:
    branches: [ main ]

permissions: {} # lock everything by default (least-privilege)

jobs:
  linkCheck:
    name: Link Checking
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: LinkCheck
        uses: Consensys-Incorporated/github-actions/docs-link-check@3a2429772a5d3653f0662a6a66299cad96e74196 # main
        with:
          CONFIG_FILE: '.linkspector.yml'
