---
name: Check for lint errors

on:
  pull_request:
    branches: [ main ]

permissions: {} # lock everything by default (least-privilege)

jobs:
  lint:
    name: Lint Code Base, Spelling
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint code
        uses: Consensys/github-actions/docs-lint-all@main

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.{md,mdx,json,ts,js,tsx,jsx,css}

      - name: Prettier check
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npx prettier --check ${{ steps.changed-files.outputs.all_changed_files }}
