---
name: Check for lint errors

on:
  pull_request:
    branches: [ main ]

permissions: {} # lock everything by default (least-privilege)

jobs:
  lint:
    name: Lint Code Base, Spelling
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Lint code
        uses: Consensys/github-actions/docs-lint-all@31dbb917dd78b1dc18b4838a2d7d598b359b834f # main

      - name: Lint markdown
        uses: Consensys/github-actions/docs-lint-markdown@68e0677c7c567c2447fc82d43dc4fceb4b31a680 # main
