---
name: Nightly check

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

permissions: {} # lock everything by default (least-privilege)

jobs:
  linkCheck:
    name: Run link check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: LinkCheck
        uses: Consensys/github-actions/docs-link-check@3a2429772a5d3653f0662a6a66299cad96e74196 # main
        with:
          CONFIG_FILE: .linkspector.yml

  slackNotification:
    needs: linkCheck
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    permissions: {}   # zero scopes
    steps:
      - name: Slack Notification
        uses: Consensys/github-actions/slack-notify@31dbb917dd78b1dc18b4838a2d7d598b359b834f # main
        with:
          SLACK_CHANNEL: doc-ci-alerts
          SLACK_COLOR: danger
          SLACK_TITLE: Linea docs nightly build - Failure
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: true
